project_name: pkg

builds:
  - skip: true

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

milestones:
  - repo:
      owner: axiomhq
      name: pkg
    close: true
    fail_on_error: false

release:
  github:
    owner: axiomhq
    name: pkg
  prerelease: auto
  name_template: "Common Go Packages v{{.Version}}"
